services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: company-wiki-backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=company_wiki
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - JWT_SECRET=supersecretkey123
      - REFRESH_SECRET=anotherSuperSecret456
    depends_on:
      - db
      - elasticsearch
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx wait-port db:3306 && npx ts-node src/seeder.ts && npx ts-node-dev --respawn src/server.ts"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: company-wiki-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:3000
    depends_on:
      - backend
    volumes:
      - ../frontend:/app
      - /app/node_modules
    command: npm run dev -- --host

  db:
    image: mysql:8
    container_name: company-wiki-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: company_wiki
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: company-wiki-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  db_data:
  es_data:
